export { default as UserLogo } from "./users.jpg";
export { default as HomeImg } from "./home.jpg";
export { default as Paris } from "./Paris.jpg";
export { default as newYork } from "./newYork.jpg";
export { default as Sydney } from "./Sydney.jpg";
export { default as mugchina } from "./mugchina.jpg";
export { default as video1 } from "./video1.mp4";
export { default as video2 } from "./video2.mp4";
export { default as video3 } from "./video3.mp4";